FROM dustynv/l4t-pytorch:r36.4.0
# FROM dustynv/cuda-python:r36.4.0-cu128-24.04
# Studio Labs has a Jetson Nano with L4T R36
# To see this "cat /etc/nv_tegra_release"

# #######################
# Install Apt Packages
# #######################
RUN apt update && apt upgrade -y \
    && apt install -y \
    apt-utils \
    python3-pip \
    curl \
    nano \
    vim \
    tmux \
    wget \
    git \
    jq \
    sudo \
    ranger \
    mlocate \
    x11-apps \
    python-is-python3 \
    gnome-terminal \
    && rm -rf /var/lib/apt/lists/*

# #######################
# Install Conda and python dependencies
# #######################

ENV CONDA_PLUGINS_AUTO_ACCEPT_TOS=yes
ENV CONDA_MAX_THREADS="2"
ENV PIP_INDEX_URL=https://pypi.org/simple

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh -O miniconda.sh \
    && bash miniconda.sh -b -p /opt/conda \
    && rm miniconda.sh

# Add conda to path and initialize
ENV PATH="/opt/conda/bin:$PATH"
RUN conda init bash

# Create conda environment and install packages
COPY ./environment.yml ./
RUN conda env create -f environment.yml

# Activate conda environment
ENV PATH="/opt/conda/envs/unik3d/bin:$PATH"
SHELL ["conda", "run", "-n", "unik3d", "/bin/bash", "-c"]

# RUN pip3 install --no-cache-dir \
#     numpy>=2.0.0

# #######################
# Setup .bashrc and tmux
# #######################
SHELL ["/bin/bash", "-l", "-c"]
RUN echo -e "\
    echo 'source /opt/conda/bin/activate unik3d' >> ~/.bashrc && \
    PS1='\e[1m\e[94m\u\e[97m@\e[94m\h:\e[92m\w\e[0m\e[97m#\e[0m '\n\
    " >> ~/.bashrc

RUN echo -e "set -g mouse on" >> /root/.tmux.conf

# #######################
# Setup entrypoint
# #######################
COPY ./docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"] 